# Generated by Django 6.0 on 2025-12-14 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(choices=[('un', 'Unidad'), ('gr', 'Gramos'), ('mt', 'Metros')], default='un', max_length=5)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen_principal', models.ImageField(upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(help_text='Email, Teléfono o Usuario RRSS', max_length=200)),
                ('descripcion_solicitud', models.TextField()),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='referencias_clientes/')),
                ('fecha_entrega_deseada', models.DateField(blank=True, null=True)),
                ('plataforma', models.CharField(choices=[('web', 'Sitio Web'), ('fb', 'Facebook'), ('ig', 'Instagram'), ('wpp', 'WhatsApp'), ('presencial', 'Presencial')], default='web', max_length=20)),
                ('estado_pedido', models.CharField(choices=[('solicitado', 'Solicitado 📩'), ('aprobado', 'Aprobado ✅'), ('proceso', 'En Proceso 🎨'), ('realizada', 'Realizada 🛠'), ('entregada', 'Entregada 📦'), ('finalizada', 'Finalizada ✨'), ('cancelada', 'Cancelada ❌')], default='solicitado', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('token_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTienda.producto')),
            ],
        ),
    ]
