# Generated by Django 5.1.6 on 2025-12-16 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion_categoria', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100, verbose_name='Nombre del Insumo')),
                ('tipo_insumo', models.CharField(max_length=100, verbose_name='Tipo de Insumo')),
                ('cantidad_disponible_insumo', models.PositiveIntegerField(verbose_name='Cantidad Disponible del Insumo')),
                ('marca_insumo', models.CharField(max_length=50, verbose_name='Marca del Insumo')),
                ('color_insumo', models.CharField(max_length=30, verbose_name='Color del Insumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('cliente_contacto', models.CharField(max_length=100, verbose_name='Contacto del cliente')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_solicitada', models.DateField(blank=True, null=True, verbose_name='Fecha Solicitada del Pedido')),
                ('origen_pedido', models.CharField(choices=[('FAC', 'Facebook'), ('IG', 'Instagram'), ('WHA', 'WhatsApp'), ('PRE', 'Presencial'), ('WEB', 'Sitio Web'), ('OTR', 'Otro')], max_length=10, verbose_name='Origen del Pedido')),
                ('origen_otro', models.CharField(blank=True, max_length=100, verbose_name='Origen (Otro)')),
                ('estado_pedido', models.CharField(choices=[('SOL', 'Solicitado'), ('APR', 'Aprobado'), ('EPR', 'En proceso'), ('REA', 'Realizado'), ('ENT', 'Entregado'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='SOL', max_length=3, verbose_name='Estado del Pedido')),
                ('estado_pago', models.CharField(choices=[('PEN', 'Pendiente'), ('PAR', 'Parcial'), ('PAG', 'Pagado'), ('REM', 'Reembolsado')], default='PEN', max_length=3, verbose_name='Estado del Pago')),
                ('token_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Pedido')),
                ('producto_referencia', models.ImageField(blank=True, null=True, upload_to='./static/media/pedidos/referencias/', verbose_name='Imagen de referencia')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ImagenPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='./static/media/pedidos/referencias', verbose_name='Imagenes de Referencia')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appTienda.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Imagen de pedido',
                'verbose_name_plural': 'Imágenes de pedidos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion_producto', models.TextField(verbose_name='Descripción del producto')),
                ('precio_base_producto', models.PositiveIntegerField(verbose_name='Precio del Producto')),
                ('producto_destacado', models.BooleanField(default=False, verbose_name='Producto Destacado Sí/No')),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='appTienda.categoria', verbose_name='Categoria del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='appTienda.producto'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='./static/media/productos/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appTienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden'],
            },
        ),
    ]
