# Generated by Django 5.1.6 on 2025-12-16 17:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpedido',
            name='imagen',
            field=models.ImageField(upload_to='pedidos/referencias/', verbose_name='Imagenes de Referencia'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='color_insumo',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/referencias/', verbose_name='Imagen de referencia'),
        ),
    ]
